#!/bin/bash
#SBATCH --job-name=yayayaya             # Job name
#SBATCH --output=output.%A.txt   # Standard output and error log
#SBATCH --nodes=1                   # Run all processes on a single node    
#SBATCH --ntasks=1                  # Run on a single CPU
#SBATCH --mem=40G                   # Total RAM to be used
#SBATCH --cpus-per-task=64          # Number of CPU cores
#SBATCH --gres=gpu:1                # Number of GPUs (per node)
#SBATCH -p gpu                      # Use the gpu partition
#SBATCH --time=12:00:00             # Specify the time needed for your experiment
#SBATCH --qos=gpu-8                 # To enable the use of up to 8 GPUs

hostname
mkdir /tmp/yahia.dalbah
cd /tmp/yahia.dalbah
mkdir /tmp/yahia.dalbah/data_root0
cp /l/users/yahia.dalbah/DATA_ROOT_TMP/* /tmp/yahia.dalbah/data_root0
# download all zip files and unzip
cd data_root0
unzip TRAIN_RAD_H.zip
unzip TRAIN_CAM_0.zip
unzip TEST_RAD_H.zip
unzip TRAIN_RAD_H_ANNO.zip
unzip CAM_CALIB.zip

# make folders for data and annotations
mkdir sequences
mkdir annotations

# rename unzipped folders
mv TRAIN_RAD_H sequences/train
mv TRAIN_CAM_0 train
mv TEST_RAD_H sequences/test
mv TRAIN_RAD_H_ANNO annotations/train

# merge folders and remove redundant
rsync -av train/ sequences/train/
rm -r train
python /home/yahia.dalbah/RODNet_testing/tools/prepare_dataset/prepare_data.py \
--config /home/yahia.dalbah/RODNet_testing/configs/config_rodnet_hg1v2_win16_mnet.py \
--data_root /tmp/yahia.dalbah/data_root0/ --split train,test --out_data_dir /tmp/yahia.dalbah/Pickle0


python /home/yahia.dalbah/RODNet_testing/tools/train.py \
--config /home/yahia.dalbah/RODNet_testing/configs/MaxVIT2.py \
--data_dir /tmp/yahia.dalbah/Pickle0 \
--resume_from /l/users/yahia.dalbah/store/Axial-202335530226-110550/epoch_13_final.pkl \
--log_dir /l/users/yahia.dalbah/store/ \
--vis_train 0

EOL

