#!/bin/bash
#SBATCH --job-name=yayayaya             # Job name
#SBATCH --output=test.%A.txt   # Standard output and error log
#SBATCH --nodes=1                   # Run all processes on a single node    
#SBATCH --ntasks=1                  # Run on a single CPU
#SBATCH --mem=40G                   # Total RAM to be used
#SBATCH --cpus-per-task=64          # Number of CPU cores
#SBATCH --gres=gpu:1                # Number of GPUs (per node)
#SBATCH -p gpu                      # Use the gpu partition
#SBATCH --time=12:00:00             # Specify the time needed for your experiment
#SBATCH --qos=gpu-8                 # To enable the use of up to 8 GPUs

hostname
# mkdir /tmp/yahia.dalbah
# cd /tmp/yahia.dalbah
# mkdir /tmp/yahia.dalbah/data_root_test
# cp /l/users/yahia.dalbah/DATA_ROOT_TMP/* /tmp/yahia.dalbah/data_root_test
# # download all zip files and unzip
# cd data_root_test
# unzip TRAIN_RAD_H.zip
# unzip TRAIN_CAM_0.zip
# unzip TEST_RAD_H.zip
# unzip TRAIN_RAD_H_ANNO.zip
# unzip CAM_CALIB.zip

# # make folders for data and annotations
# mkdir sequences
# mkdir annotations

# # rename unzipped folders
# mv TRAIN_RAD_H sequences/train
# mv TRAIN_CAM_0 train
# mv TEST_RAD_H sequences/test
# mv TRAIN_RAD_H_ANNO annotations/train

# # merge folders and remove redundant

# rsync -av train/ sequences/train/
# rm -r train
# python /home/yahia.dalbah/RODNet_2d/RODNet_testing/tools/prepare_dataset/prepare_data.py \
# --config /home/yahia.dalbah/RODNet_2d/RODNet_testing/configs/config_rodnet_hg1v2_win16_mnet.py \
# --data_root /tmp/yahia.dalbah/data_root_test/ --split train,test --out_data_dir /tmp/yahia.dalbah/Pickletest ; 




rm -rf /l/users/yahia.dalbah/results/test55
mkdir /l/users/yahia.dalbah/results/test55


#rm -rf /l/users/yahia.dalbah/results/output_final
mkdir /l/users/yahia.dalbah/results/output_final
mkdir /l/users/yahia.dalbah/zipfiles/



python /home/yahia.dalbah/RODNet_testing/tools/test.py \
--config /home/yahia.dalbah/RODNet_testing/configs/Axial.py \
--data_dir /l/users/yahia.dalbah/Pickle \
--checkpoint /l/users/yahia.dalbah/store/Axial-20230227-100152/epoch_27_final.pkl \
--res_dir /l/users/yahia.dalbah/results/test55/ ;




python /home/yahia.dalbah/RODNet_testing/tools/format_transform/convert_rodnet_to_rod2021-slurm1.py \
--result_dir /l/users/yahia.dalbah/results/test55/Axial-20230227-100152/ \
--final_dir /l/users/yahia.dalbah/results/output_final/test55 ;





cd /l/users/yahia.dalbah/results/output_final/test55/

zip /l/users/yahia.dalbah/zipfiles/5epoch_yaya_final.zip *.txt

EOL